### ISSUE TITLE
issue on archlinux while running rsautotor

### ISSUE THREAD

**Issue by aarushlohit** [ryzeon-dev/rsAutoTor#1]
thread 'main' panicked at src/main.rs:38:32:
called `Result::unwrap()` on an `Err` value: Error { description: "Couldn't connect to server", code: 7, extra: Some("Failed to connect to 127.0.0.1 port 9050 after 0 ms: Couldn't connect to server") }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ryzeon-dev** [comment]
is the Tor service active on your system?

**Comment by ryzeon-dev** [comment]
in any case, TOR availability and activity check has been implemented in the last update. Your bug report has been fixed. Thank you for your feedback
